# Generated by Django 4.1.2 on 2022-10-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=500)),
                ('manset', models.TextField(max_length=500)),
                ('kisaAciklama', models.TextField(max_length=500)),
                ('uzunAciklama', models.TextField(max_length=50000)),
                ('resim', models.FileField(blank=True, null=True, upload_to='duyurular/')),
            ],
        ),
    ]
