# Generated by Django 4.1.2 on 2022-10-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhywApp', '0002_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='baslikar',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='basliken',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='kisaAciklamaar',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='kisaAciklamaen',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='mansetar',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='manseten',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='uzunAciklamaar',
            field=models.TextField(max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='uzunAciklamaen',
            field=models.TextField(max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='kisaAciklama',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='uzunAciklama',
            field=models.TextField(max_length=50000, null=True),
        ),
    ]
