# Generated by Django 4.1.2 on 2022-10-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhywApp', '0003_duyuru_baslikar_duyuru_basliken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='baslik',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='baslikar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='basliken',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='kisaAciklama',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='kisaAciklamaar',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='kisaAciklamaen',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='manset',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='mansetar',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='manseten',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='uzunAciklama',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='uzunAciklamaar',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='duyuru',
            name='uzunAciklamaen',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
