# Generated by Django 4.1.2 on 2022-12-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhywApp', '0005_duyuru_baslangic_duyuru_bitis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yazilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=500)),
                ('yazi', models.CharField(max_length=500)),
                ('gonderimTarihi', models.DateField(blank=True, null=True)),
                ('kabulTarihi', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Demo',
        ),
    ]
